from pathlib import Path
from cryptography import x509
from cryptography.x509.oid import NameOID
from cryptography.hazmat.primitives import serialization, hashes

# Output paths for client certificates (copied from factory certs)
CLIENT_KEY_PATH = "certificates/client.key.pem"
CLIENT_CSR_PATH = "certificates/client.csr.pem"
CLIENT_CERTIFICATE_PATH = "certificates/client.crt.pem"


def prepare_factory_cert(
    vin: str,
    factory_cert_path: str,
    factory_key_path: str,
) -> tuple[str, str, str]:
    """
    Prepare factory certificate for use by the vehicle client.

    The factory certificate is already generated by the shell script
    (generate-factory-cert.sh for local PKI or generate-factory-cert-gcp.sh for remote PKI).
    This function copies the certificates to the working directory and generates a CSR.

    Args:
        vin: Vehicle Identification Number
        factory_cert_path: Path to the factory certificate chain (PEM)
        factory_key_path: Path to the factory private key (PEM)

    Returns:
        Tuple of (key_path, csr_path, cert_path) for use in registration
    """
    print("Preparing factory certificate...")

    # Verify factory cert and key exist
    factory_cert = Path(factory_cert_path)
    factory_key = Path(factory_key_path)

    if not factory_cert.exists():
        raise FileNotFoundError(f"Factory certificate not found: {factory_cert_path}")
    if not factory_key.exists():
        raise FileNotFoundError(f"Factory key not found: {factory_key_path}")

    # Create certificates directory
    Path("certificates").mkdir(parents=True, exist_ok=True)

    # Copy factory key to client key location
    client_key_path = Path(CLIENT_KEY_PATH)
    client_key_path.write_bytes(factory_key.read_bytes())
    print(f"  Copied factory key to {CLIENT_KEY_PATH}")

    # Copy factory cert to client cert location
    client_cert_path = Path(CLIENT_CERTIFICATE_PATH)
    client_cert_path.write_bytes(factory_cert.read_bytes())
    print(f"  Copied factory certificate to {CLIENT_CERTIFICATE_PATH}")

    # Load the factory key to generate CSR
    key_data = factory_key.read_bytes()
    private_key = serialization.load_pem_private_key(key_data, password=None)

    # Generate CSR from the factory key (needed for registration)
    csr = x509.CertificateSigningRequestBuilder().subject_name(x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, f"VIN:{vin} DEVICE:{vin}"),
        x509.NameAttribute(NameOID.ORGANIZATION_NAME, "Vehicle Manufacturer"),
    ])).sign(private_key, hashes.SHA256())

    csr_bytes = csr.public_bytes(encoding=serialization.Encoding.PEM)

    # Save CSR
    client_csr_path = Path(CLIENT_CSR_PATH)
    client_csr_path.write_bytes(csr_bytes)
    print(f"  Generated CSR at {CLIENT_CSR_PATH}")

    print("Factory certificate prepared successfully.")

    return CLIENT_KEY_PATH, CLIENT_CSR_PATH, CLIENT_CERTIFICATE_PATH
