apiVersion: v1
kind: ServiceAccount
metadata:
  name: data-web-client-ksa
  namespace: sample-services
  labels:
    {{- include "data-web-client.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.gcp.serviceAccountEmail | quote }}
